# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestUntitled():
    def setup_method(self, method):
        self.driver = webdriver.Chrome(r"C:\Users\SALEEM_\Desktop\chrome driver\chromedriver.exe")
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def wait_for_window(self, timeout=2):
        time.sleep(round(timeout / 1000))
        wh_now = self.driver.window_handles
        wh_then = self.vars["window_handles"]
        if len(wh_now) > len(wh_then):
            return set(wh_now).difference(set(wh_then)).pop()

    def test_untitled(self):
        self.driver.get("https://www.flipkart.com/")
        self.driver.set_window_size(1382, 744)
        self.driver.find_element(By.LINK_TEXT, "Login").click()
        self.driver.find_element(By.CSS_SELECTOR, ".IiD88i:nth-child(1) > .\\_2IX_2-").click()
        #self.driver.find_element(By.CSS_SELECTOR, ".\\_1Z69nn").send_keys("9701604746")
        self.driver.find_element(By.CSS_SELECTOR, ".\\_1Z69nn").click()
        self.driver.find_element(By.CSS_SELECTOR, ".\\_1Z69nn").send_keys("9701604746")
        self.driver.find_element(By.CSS_SELECTOR, ".\\_3mctLh").send_keys("6281861488")
        self.driver.find_element(By.CSS_SELECTOR, ".\\_3AWRsL").click()
        #self.driver.find_element(By.NAME, "q").click()
        #self.driver.find_element(By.LINK_TEXT, "mobiles").click()
        #self.vars["window_handles"] = self.driver.window_handles
        #self.driver.find_element(By.CSS_SELECTOR, ".\\_1AtVbE:nth-child(2) > .\\_13oc-S .CXW8mj").click()
        #self.vars["win2520"] = self.wait_for_window(2000)
        #self.driver.switch_to.window(self.vars["win2520"])

